version: "2"
services:
    proxy:
        image: nginx:1.13.6-alpine
        container_name: trainline_proxy
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available/default:/etc/nginx/conf.d/default.conf
            #- ../frontend:/usr/share/nginx/html
            - /var/log/nginx:/var/log/nginx
        depends_on: 
            - api
        network_mode: host

    api:
        image: keymetrics/pm2:8
        container_name: trainline_api
        volumes:
            - ../api:/app
        environment:
            - NODE_ENV=production
        network_mode: host

networks:
    default:
        external:
            name: "host"